language: node_js

node_js:
  - "7"

cache:
  directories:
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: danval85/gulp-framework
  bucket: deployment-pipeline-s3
  region: eu-west-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: deployment-pipeline-s3
  key: latest.zip
  bundle_type: zip
  application: gulp-framework
  deployment_group: continuous-delivery
  region: eu-west-1
  on: *2

before_script:
  - npm install -g gulp-cli

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
  - gulp test-build